[build]
  publish = "build"
  command = "npm run build"

[[plugins]]
  package = "./node_modules/@sentry/netlify-build-plugin"

  [plugins.inputs]
    sentryOrg = "waterloo-sparkling-water"
    sentryProject = "netlify-react-test"